version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./postgres-external-config.conf:/var/lib/postgresql/data/postgresql.conf
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
    ports:
      - "5432:5432"

  java-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
  
  go-service:
    build:
      context: /go/import_export/src
      dockerfile: Dockerfile
    volumes:
      - ./go/import_export/src:/app
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    restart: always
    environment:
      HOSTNAME: postgres
      USER: postgres
      PASSWORD: admin
      DATABASE: db
      PORT: 5432

  encrytion-service:
    build:
      context: /encryption-app/encryption/encryption
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always

volumes:
  postgres-data: {}