version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  java-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    environment:
      JWT_TOKEN: "VAULTSHIELD_KEY"
      SPRING_PROFILES_ACTIVE: docker
  
  go-service:
    build:
      context: /go/src/import_export/src
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always
    environment:
      HOSTNAME: localhost
      USER: postgres
      PASSWORD: admin
      DATABASE: db
      PORT: 5432
