version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"


  java-service:
    image: openjdk:17
    volumes:
      - .:/usr/src/vaultshield
    working_dir: /usr/src/vaultshield
    command: java -jar target/vault-shield-0.0.5-SNAPSHOT.jar
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    environment:
      JWT_TOKEN: "VAULTSHIELD_KEY"
      SPRING_PROFILES_ACTIVE: docker