spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

JWT_SECRET: ${JWT_SECRET:5468576D5A7134743777217A25432A462D4A614E635266556A586E3272357538}
JWT_RECOVER: ${JWT_RECOVER:6QDOHA126QXGFL5MMOZMSV12V5LK986BWKXHFNAMAFTOQFRINY4E2F5162341412}

springfox:
  documentation:
    swagger-ui:
      enabled: true
    api-docs:
      path: /v3/api-docs

password-manager:
  jwtKey: ${JWT_TOKEN:default}