# This configuration is prepared for local environments where you want to experiment something
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/db} # Preconfigured for postgres 5433, change it for your needs
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin} # Example default database password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

JWT_SECRET: ${JWT_SECRET:5468576D5A7134743777217A25432A462D4A614E635266556A586E3272357538} # Example default key
JWT_RECOVER: ${JWT_RECOVER:6QDOHA126QXGFL5MMOZMSV12V5LK986BWKXHFNAMAFTOQFRINY4E2F5162341412} # Example default key

springfox:
  documentation:
    swagger-ui:
      enabled: true
    api-docs:
      path: /v3/api-docs