spring:
  datasource:
    url: ${SPRING_MYSQl_URL:jdbc:mariadb://localhost:3306/password_manager}
    username: ${SPRING_MYSQl_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:mypassword}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

springfox:
  documentation:
    swagger-ui:
      enabled: true
    api-docs:
      path: /v3/api-docs