# Deployment environment for docker containers,
# specialized for deploying production in a container orchestration
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

JWT_SECRET: ${JWT_SECRET} # Handled by environment variables or github/deploy secret
JWT_RECOVER: ${JWT_RECOVER} # Handled by environment variables or github/deploy secret

springfox:
  documentation:
    swagger-ui:
      enabled: true
    api-docs:
      path: /v3/api-docs